#' Summarize a set of records downloaded from VertNet.
#'
#' Creates a simple summary of data returned by a VertNet search.
#'
#' @param input A data frame as generated by calling vertsearch(), 
#'    searchbyterm() or spatialsearch()
#' @return A list of summary statistics
#' @details \code{vertsummary} provides information on the sources, types and extent
#'    of data returned by a VertNet search.
#' @examples \dontrun{
#'
#' recs <- vertsearch("Junco hyemalis")  # get occurrence records
#' recsum <- vertsummary(out)            # summarize occurrence records
#' 
#' rs <- vertsummary(vertsearch("Oncorhynchus clarki henshawi"))
#' }
#' @export

vertsummary <- function(input = NULL)

{

  vertsumwrapper(input)
  
}